apiVersion: v1
kind: Pod
metadata:
  name: bking2-ib-double-descent
  labels:
    user: bking2
    k8s-app: bking2-debug
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvidia.com/gpu.product
            operator: In
            values:
            - NVIDIA-GeForce-GTX-1080-Ti
            - NVIDIA-GeForce-RTX-2080-Ti
            - NVIDIA-GeForce-RTX-3090
            - NVIDIA-TITAN-Xp
            - Tesla-T4
          - key: kubernetes.io/hostname
            operator: NotIn
            values:
              - osg-houston-stashcache.nrp.internet2.edu
  imagePullSecrets:
  - name: ib-double-descent-registry-creds
  containers:
  - name: bking2-ib-double-descent
    image: gitlab-registry.nrp-nautilus.io/cse208-ib-double-descent/ib_double_descent:latest
    envFrom:
      - secretRef:
          name: ib-double-descent-deploy-key
      - secretRef:
          name: ib-double-descent-wandb-key
    resources:
      limits:
        memory: 32Gi
        cpu: 16
        nvidia.com/gpu: "1"
      requests:
        memory: 32Gi
        cpu: 16
        nvidia.com/gpu: "1"
    command: [ "/bin/sh" ]
    # commmand does the following:
    # 1) set up the github deployment (SSH) key: we store the relevant secrets as environment variables, because
    #    injecting them as files makes root the owner, and the container needs to run as non-privileged user. We
    #    also add githubs public keys to known_hosts to bypass the interactive fingerprint check on later clones
    # 2) clone repo: this clones the repo into temp, since the folder already exists and contains our venv
    #    definition that we don't want to overwrite. Then, we move the .git definition into the folder (which had
    #    none to begin with), and fetch and pull. This doesn't yet overwrite files, we then need to do a hard reset to
    #    origin/main (assuming this is the branch we are always running jobs from). This step allows us to not re-build
    #    the docker container for every code change, only those which are important to it.
    # 3) log in the huggingface for private model access and saving
    # 4) start the SSH server w/ sshd
    args:
      - -c
      - >-
        echo "$SSH_PRIVATE_KEY" > /home/ibdd/.ssh/id_rsa &&
        echo "$SSH_PUBLIC_KEY" > /home/ibdd/.ssh/id_rsa.pub &&
        chmod 644 /home/ibdd/.ssh/id_rsa.pub &&
        chmod 600 /home/ibdd/.ssh/id_rsa &&
        echo "github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==" >> /home/ibdd/.ssh/known_hosts &&
        echo "github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=" >> /home/ibdd/.ssh/known_hosts &&
        echo "github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl" >> /home/ibdd/.ssh/known_hosts &&
        cd /home/ibdd &&
        git clone git@github.com:kingb12/ib-double-descent.git temp &&
        mv temp/.git ib_double_descent/.git &&
        rm -rf temp &&
        cd ib_double_descent &&
        git fetch && git pull && git reset --hard origin/main &&
        echo "debug pod ready to start" &&
        /usr/sbin/sshd -D -f /opt/ssh/sshd_config -E /tmp/sshd.log
    volumeMounts:
    - mountPath: /data/users/ibdd
      name: ib-dd-data-volume
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: PreferNoSchedule
    key: nvidia.com/gpu
    operator: Exists
  volumes:
    - name: ib-dd-data-volume
      persistentVolumeClaim:
        claimName: ib-dd-data-volume