name: build

on:
  push:
    # below: trying to avoid builds for changes that don't affect the environment definition, since they are
    # long-running & my GH Actions usage is limited. The repo is installed in edit mode in the container definition, but
    # this means the experiment needs to clone the appropriate revision into place before starting, or it risks running
    # stale code.
    paths:
      - 'k8s/Dockerfile'
      - 'requirements.txt'
      - '.github/workflows/docker_build.yml'
      - '.github/workflows/docker_build.yml'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Nautilus Gitlab Docker Registry
        uses: docker/login-action@v2
        with:
          registry: gitlab-registry.nrp-nautilus.io
          username: "ibdd"
          password: ${{ secrets.GITLAB_DOCKER_REGISTRY_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          file: k8s/Dockerfile
          tags: |
            gitlab-registry.nrp-nautilus.io/cse208-ib-double-descent/ib_double_descent:latest
